module.exports = [
"thinking intensely", 
"waiting for death", 
"staring at camera", 
"attacking", 
"drinking",
"fighting",
"spitting fire",
"experimenting",
"hallucinating",
"snarling", 
"laughing", 
"lazer blasting",
"doing telekenesis",
"hunting", 
"wearing hoodie", 
"with glowing eyes", 
"smoking a joint", 
"wearing a t-shirt", 
"screeching loudly", 
"wearing beanie and goggles", 
"wearing short shorts", 
"wearing sunglasses", 
"salivating", 
"growing", 
"working at drive-thru", 
"exploring", 
"tripping on lsd", 
"with cool hair and cheap clothes", 
"discovering ancient gold", 
"surrounded by money", 
"dressed in cheap ragged clothes", 
"looking at me", 
"working on laptop", 
"talking on phone", 
"dance passionately",
"dressing up in costume",
"drinking and getting drunk",
"playing the guidar",
"singing loudly",
'playing harmonica',
'juggling flaming pins',
'getting married',
'being born',
'riding a horse',
'sitting at the bar',
'sleeping on the bus',
'sleep walking',
"eating good food", 
"watching tv", 
"in bathtub",
"praying",
"finding treasure",
"being baptized",
"Pogonotomizing",
"Pluviophiling",
"Philematology",
"Crapulence",
"Cacoethes",
"Obnubilating",
"tattooed",
"dressed fancy",
"smoking marijuana",
"passing joint",
"smoking bong",
"surfing",
"skateboarding",
"skiing",
"snowboarding",
"dreaming",
"driving racecar",
"rising from the earth",
"Eleutheromania",
"Pluviophagous",
"Somnambulating",
"Heterodoxing",
"Apodyopsis",
"Odylic",
"Quomodocunquizing",
"Chucklefying",
"Gigglefying",
"Hilarifying",
"typing on laptop",
"Laughterizing",
"Amusementating",
"Jokifying",
"Snickeringly",
"Lollipopping",
"Chortlingly",
"Grinningly",
"Smirkingly",
"Sniggering",
"Wittyfying",
"Humorizing",
"Comedifying",
"Terrifying",
"Menacing",
"Horrifying",
"Petrifying",
"Intimidating",
"Frightening",
"Haunting",
"Chilling",
"Creeping",
"Shivering",
"Quivering",
"Trembling",
"Spooking",
"Startling",
"Dance",
  "Sing karaoke",
  "Play beer pong",
  "Socialize with friends",
  "Drink cocktails",
  "Play party games",
  "Take group photos",
  "Eat appetizers",
  "Listen to music",
  "Watch movies",
  "Make new friends",
  "Play video games",
  "Eat dinner",
  "Have a BBQ",
  "Play card games",
  "Play board games",
  "Watch sports",
  "Watch a live band",
  "Go swimming",
  "Go to the beach",
  "Go on a hike",
  "Have a bonfire",
  "Tell stories",
  "Have a costume party",
  "Have a themed party",
  "Have a murder mystery party",
  "Play truth or dare",
  "Play spin the bottle",
  "Have a scavenger hunt",
  "Have a talent show",
  "Make cocktails",
  "Make mocktails",
  "Eat cake",
  "Have a potluck",
  "Have a bake-off",
  "Have a cook-off",
  "Have a chili cook-off",
  "Have a BBQ cook-off",
  "Have a cocktail competition",
  "Have a dance competition",
  "Have a karaoke competition",
  "Have a costume contest",
  "Have a beauty contest",
  "Have a trivia competition",
  "Have a spelling bee",
  "Have a poetry slam",
  "Have a stand-up comedy night",
  "Have a game show night",
  "Have a movie night",
  "Have a board game night",
  "Have a card game night",
  "Have a sports night",
  "Have a video game tournament",
  "Have a pool tournament",
  "Have a poker tournament",
  "Have a beer tasting",
  "Have a wine tasting",
  "Have a cocktail tasting",
  "Have a chocolate tasting",
  "Have a cheese tasting",
  "Have a fondue party",
  "Have a sushi party",
  "Have a taco bar",
  "Have a pizza party",
  "Have a burger bar",
  "Have a hot dog bar",
  "Have a fondue party",
  "Have a brunch party",
  "Have a breakfast for dinner party",
  "Have a dessert bar",
  "Have a candy bar",
  "Have a chocolate fountain",
  "Have a popcorn bar",
  "Have a nacho bar",
  "Have a guacamole bar",
  "Have a salsa bar",
  "Have a beer and cheese pairing party",
  "Have a wine and cheese pairing party",
  "Have a cheese fondue party",
  "Have a cocktail party",
  "Have a garden party",
  "Have a tea party",
  "Have a coffee tasting",
  "Have a craft beer tasting",
  "Have a Scotch tasting",
  "Have a bourbon tasting",
  "Have a whiskey tasting",
  "Have a rum tasting",
  "Have a gin tasting",
  "Have a vodka tasting",
  "Have a tequila tasting",
  "Have a sake tasting",
  "Have a margarita party",
  "Have a mojito party",
  "Have a martini party",
  "Have a sangria party",
  "Have a beer and pizza party",
  "Have a wine and cheese party",
  "Have a hot tub party",
  "Have a spa party",
  "Have a nail party",
  "Have a makeup party",
  "Have a hair styling party",
  "Have a massage party"]