module.exports = [  
"Extreme Wide Shot",  
"Very Wide Shot",  
"Wide Shot",  
"Medium Shot",  
"Medium Close-Up",  
"Close-Up",  
"Extreme Close-Up",  
"Over-The-Shoulder Shot",  
"Point of View Shot",  
"Low Angle Shot",  
"High Angle Shot",  
"Dutch Angle Shot",  
"Bird's Eye View Shot",  
"Aerial Shot",  
"Tracking Shot",  
"Crane Shot",  
"Steadicam Shot",  
"Handheld Shot",  
"Zoom Shot"]
