module.exports = [
  "Pablo Picasso",
  "Vincent van Gogh",
  "Leonardo da Vinci",
  "Claude Monet",
  "Salvador Dali",
  "Michelangelo",
  "Rembrandt",
  "Frida Kahlo",
  "Jackson Pollock",
  "Henri Matisse",
  "Edvard Munch",
  "Andy Warhol",
  "Georgia O'Keeffe",
  "Gustav Klimt",
  "Paul Cezanne",
  "Wassily Kandinsky",
  "Edgar Degas",
  "Rene Magritte",
  "Mark Rothko",
  "Marc Chagall",
  "Roy Lichtenstein",
  "Caravaggio",
  "Jan Vermeer",
  "Peter Paul Rubens",
  "Diego Velazquez",
  "Titian",
  "Johannes Vermeer",
  "Goya",
  "Egon Schiele",
  "Paul Gauguin",
  "Francisco de Zurbaran",
  "Banksy",
  "Keith Haring",
  "Jeff Koons",
  "Anselm Kiefer",
  "Gerhard Richter",
  "Lucian Freud",
  "Yayoi Kusama",
  "Kara Walker",
  "Ai Weiwei",
  "Damien Hirst",
  "Marina Abramovic",
  "Yoko Ono",
  "David Hockney",
  "Joan Miro",
  "Richard Serra",
  "Ellsworth Kelly",
  "Cindy Sherman",
  "Chuck Close",
  "Robert Rauschenberg",
  "Sol LeWitt",
  "Agnes Martin",
  "Brice Marden",
  "Mary Cassatt",
  "Winslow Homer",
  "John Singer Sargent",
  "Willem de Kooning",
  "Robert Motherwell",
  "Helen Frankenthaler",
  "Frank Stella",
  "Robert Ryman",
  "Jasper Johns",
  "Richard Diebenkorn",
  "Alex Katz",
  "Cy Twombly",
  "Julie Mehretu",
  "Kehinde Wiley",
  "Zhang Xiaogang",
  "Liu Xiaodong",
  "Yue Minjun",
  "Fang Lijun",
  "Zeng Fanzhi",
  "Zhou Chunya",
  "Wang Guangyi",
  "Huang Yongping",
  "Liu Wei",
  "Huang Rui",
  "Qiu Zhijie",
  "Xu Bing",
  "Gu Wenda",
  "Zhan Wang",
  "Shi Guorui",
  "Xu Zhen",
  "Yang Fudong",
  "Yan Pei-Ming",
  "Zhu Jinshi",
  "Cai Guo-Qiang",
  "Liu Bolin",
  "Luo Zhongli",
  "Wu Guanzhong",
  "Li Shan",
  "Xu Beihong",
  "Lin Fengmian",
  "Zao Wou-Ki",
  "Sanyu",
  "Chu Teh-Chun",
  "Chen Chengbo",
  "Li Keran",
  "Fu Baoshi",
  "Qi Baishi",
  "Xu Shiqi",
  "Wang Meng",
  "Ren Xiong",
  "Ren Bonian",
  "Wu Changshuo"
];
