module.exports = [
  'Adam', 
'Eve', 
'Cain', 
'Abel', 
'Noah', 
'Shem', 
'Ham', 
'Japheth', 
'Lot', 
'Abraham',
  'Sarah', 
'Hagar', 
'Isaac', 
'Rebekah', 
'Jacob', 
'Esau', 
'Leah', 
'Rachel', 
'Joseph', 
'Benjamin',
  'Judah', 
'Tamar', 
'Moses', 
'Miriam', 
'Aaron', 
'Joshua', 
'Caleb', 
'Rahab', 
'Deborah', 
'Gideon',
  'Samson', 
'Delilah', 
'Ruth', 
'Naomi', 
'Boaz', 
'Hannah', 
'Eli', 
'Samuel', 
'Saul', 
'Jonathan',
  'David', 
'Michal', 
'Bathsheba', 
'Nathan', 
'Solomon', 
'Rehoboam', 
'Jeroboam', 
'Elijah', 
'Elisha',
  'Naaman', 
'Jehu', 
'Hezekiah', 
'Isaiah', 
'Manasseh', 
'Josiah', 
'Jeremiah', 
'Baruch', 
'Daniel',
  'Shadrach', 
'Meshach', 
'Abednego', 
'Ezra', 
'Nehemiah', 
'Esther', 
'Mordecai', 
'Job', 
'Eliphaz',
  'Bildad', 
'Zophar', 
'Elihu', 
'Jonah', 
'Amos', 
'Hosea', 
'Micah', 
'Joel', 
'Isaiah', 
'Haggai',
  'Zechariah', 
'Malachi', 
'John the Baptist', 
'Mary', 
'Joseph', 
'Jesus', 
'Peter', 
'Andrew', 
'James',
  'John', 
'Philip', 
'Bartholomew', 
'Thomas', 
'Matthew', 
'James (son of Alphaeus)', 'Thaddaeus',
  'Simon the Zealot', 
'Judas Iscariot', 
'Mary Magdalene', 
'Martha', 
'Lazarus', 
'Nicodemus',
  'Pontius Pilate', 
'Herod', 
'Herod Antipas', 
'Herod Agrippa', 
'Caesar Augustus', 
'Caiaphas',
  'Annas', 
'Simon of Cyrene', 
'Mary (mother of Jesus)', 'Elizabeth', 
'Zacharias', 
'Simeon', 
'Anna',
  'John (son of Zebedee)', 'Luke', 
'Timothy', 
'Titus', 
'Philemon', 
'Priscilla', 
'Aquilla',
  'Lydia', 
'Eunice', 
'Lois', 
'Dorcas', 
'Tabitha', 
'Demas', 
'Tychicus', 
'Onesimus', 
'Epaphras',
  'Mark', 
'Barnabas', 
'Silas', 
'Apollos', 
'Gaius', 
'Diotrephes', 
'Demetrius', 
'Alexander',
  'Eutychus', 
'Phoebe', 
'Junia', 
'Andronicus', 
'Euodia', 
'Syntyche', 
'Epaphroditus', 
'Archippus',
  'Nympha', 
'Aristarchus', 
'Urbanus', 
'Zenas', 
'Crescens', 
'Prisca', 
'Aquila', 
'Stephanas',
  'Fortunatus', 
'Achaicus', 
'Erastus', 
'Quartus', 
'Hermas', 
'Linus', 
'Clement', 
'Ignatius', 
"The Book of Revelation",
"The Book of Daniel",
"The Book of Isaiah",
"The Book of Exodus",
"The Book of Genesis",
"The Book of Job",
"The Book of Psalms",
"The Book of Proverbs",
"The Book of Ecclesiastes",
"The Book of Jeremiah",
"The Book of Ezekiel",
"The Book of Hosea",
"The Book of Amos",
"The Book of Micah",
"The Book of Zechariah",
"The Book of Malachi",
"The Gospel of the Nazarenes",
"The Gospel of the Ebionites",
"The Gospel of Mary Magdalene",
"The Gospel of Philip",
"The Gospel of Judas",
"The Gospel of Truth",
"The Gospel of Barnabas",
"The Gospel of Thomas Didymus",
"The Gospel of Peter",
"The Gospel of James",
"The Gospel of Nicodemus",
"The Gospel of the Infancy of Jesus Christ",
"The Book of Enoch the Prophet",
"The Book of Jasher",
"The Book of Jubilees",
"The Testament of the Twelve Patriarchs",
"The Testaments of the Twelve Patriarchs",
"The Assumption of Moses",
"The Book of Tobit",
"The Book of Judith",
"The Wisdom of Solomon",
"The Wisdom of Jesus Son of Sirach",
"The Prayer of Manasseh",
"The Epistle of Barnabas",
"The Didache",
"The Shepherd of Hermas",
"The Ascension of Isaiah",
"The Apocalypse of Peter",
"The Apocalypse of Paul",
"The Apocalypse of Thomas",
"The Coptic Apocalypse of Peter",
"The First Book of Adam and Eve",
"The Second Book of Adam and Eve",
"The Secrets of Enoch",
"The Life of Adam and Eve",
"The Book of the Secrets of Enoch",
"The Book of the Cave of Treasures",
"The Book of Adam and Eve",
"The Book of Seth",
"The Book of Solomon",
"The Book of Baruch",
"The Martyrdom of Isaiah",
"The Apocalypse of Adam",
"The Acts of Thomas",
"The Gospel of Bartholomew",
"The Gospel of Andrew",
"The Gospel of Matthew",
"The Gospel of Mark",
"The Gospel of Luke",
"The Gospel of John",
"The Acts of John",
"The Acts of Peter",
"The Acts of Paul",
"The Acts of Thomas",
"The Acts of Barnabas",
"The Acts of Philip",
"The Acts of the Apostles",
"The Epistle to the Romans",
"The First Epistle to the Corinthians",
"The Second Epistle to the Corinthians",
"The Epistle to the Galatians",
"The Epistle to the Ephesians",
"The Epistle to the Philippians",
"The Epistle to the Colossians",
"The First Epistle to the Thessalonians",
"The Second Epistle to the Thessalonians",
"The First Epistle to Timothy",
"The Second Epistle to Timothy",
"The Epistle to Titus",
"The Epistle to Philemon",
"The Epistle to the Hebrews",
"The Epistle of James",
"The First Epistle of Peter"
];
