module.exports = [  "Amun",
  "Anubis",
  "Bastet",
  "Bes",
  "Geb",
  "Hathor",
  "Horus",
  "Isis",
  "Khepri",
  "Khnum",
  "Maat",
  "Nephthys",
  "Nut",
  "Osiris",
  "Ptah",
  "Ra",
  "Sekhmet",
  "Sobek",
  "Tefnut",
  "Thoth",
  "Wadjet",
  
  // Greek gods
  "Zeus",
  "Poseidon",
  "Hades",
  "Apollo",
  "Ares",
  "Athena",
  "Demeter",
  "Dionysus",
  "Hermes",
  "Hephaestus",
  "Hera",
  "Persephone",
  "Orpheus",
  "Zeus",
  "Poseidon",
  "Hades",
  "Athena",
  "Apollo",
  "Artemis",
  "Hermes",
  "Aphrodite",
  "Hephaestus",
  "Dionysus",
  "Demeter",
  "Persephone",
  "Hera",
  "Hecate",
  "Nyx",
  "Eros",
  "Chaos",
  "Erebus",
  "Aether",
  "Gaia",
  "Uranus",
  "Cronus",
  "Rhea",
  "Helios",
  "Selene",
  "Eos",
  "Astraeus",
  "Aurora",
  "Atlas",
  "Prometheus",
  "Epimetheus",
  "Pandora",
  "Calypso",
  "Circe",
  "Hermaphroditus",
  "Narcissus",
  "Orpheus",
  "Nereus",
  "Triton",
  "Proteus",
  "Glaucus",
  "Thetis",
  "Amphitrite",
  "Leucothea",
  "Galatea",
  "Oceanus",
  "Tethys",
  "Hyperion",
  "Iapetus",
  "Coeus",
  "Phoebe",
  "Themis",
  "Asteria",
  "Lelantos",
  "Styx",
  "Achelous",
  "Eurydice",
  "Ariadne",
  "Alcestis",
  "Asclepius",
  "Astraeus",
  "Athena Nike",
  "Bia",
  "Clio",
  "Deimos",
  "Enyo",
  "Eris",
  "Ganymede",
  "Harmonia",
  "Hebe",
  "Hesperus",
  "Horae",
  "Iris",
  "Kratos",
  "Lachesis",
  "Melpomene",
  "Momus",
  "Moros",
  "Nike",
  "Nemesis",
  "Notus",
  "Ouranos",
  "Pallas",
  "Peitho",
  "Pheme",
  "Phlegethon",
  "Polyhymnia",
  "Pontus",
  "Priapus",
  "Psyche",
  "Thanatos",
  "Thalia",
  "Urania",
  "Zephyrus",
  "Aglaea",
  "Charites",
  "Clio",
  "Dike",
  "Elpis",
  "Euphrosyne",
  "Geras",
  "Horae",
  "Keres",
  "Lethe",
  "Moirai",
  "Muses",
  "Nemesis",
  "Peleus",
  "Pheme",
  "Thalia",
  "Tyche",
  "Atalanta",
  "Boreas",
  "Castor",
  "Chione",
  "Cleopatra",
  "Daphne",
  "Echo",
  "Endymion",
  "Europa",
  "Galene",
  "Hippolyta",
  "Icarus",
  "Idas",
  "Leda",
  "Medea",
  "Medusa",
  "Minos",
  "Narcissus",
  "Orion",
  "Pan",
  "Phaedra",
  "Philemon",
  "Polydectes",
"Pygmalion",
"Sisyphus",
"Siren",
"Tantalus",
"Theseus",
"Alcyone",
"Amphion",
"Ananke",
"Aristaeus",
"Atropos",
"Autolycus",
"Calliope",
"Cassandra",
"Charybdis",
"Chronos",
"Clio",
"Clotho",
"Creon",
"Dionysus",
"Electra",
"Eos",
"Erato",
"Eros",
"Europa",
"Ganymede",
"Gorgon",
"Gorgophone",
"Harpy",
"Hermione",
"Hyacinth",
"Iapetus",
"Iris",
"Ixion",
"Janus",
"Lamia",
"Laocoön",
"Leda",
"Lethe",
"Lycaon",
"Machaon",
"Melampus",
"Menelaus",
"Metis",
"Minos",
"Mnemosyne",
"Morpheus",
"Nereid",
"Nike",
"Nyx",
"Oceanid",
"Oenone",
"Orestes",
"Pandion",
"Pegasus",
"Perseus",
"Phaedra",
"Philemon",
"Polyphemus",
"Priam",
"Psyche",
"Pyramus",
"Semele",
"Sibyl",
"Silenus",
"Sphinx",
"Tethys",
"Thamyris",
"Theia",
"Tiresias",
"Tityos",
"Triptolemus",
"Zelus",

//other
"Abraxas",

  // Roman gods
  "Jupiter",
  "Neptune",
  "Pluto",
  "Apollo",
  "Mars",
  "Minerva",
  "Ceres",
  "Bacchus",
  "Mercury",
  "Vulcan",
  "Juno",
  "Proserpina",
  
  // Norse gods
  "Odin",
  "Thor",
  "Loki",
  "Baldr",
  "Freyja",
  "Frigg",
  "Hel",
  "Tyr",
  "Heimdallr",
  "Njord",
  "Skadi",
  "Aegir",
  
  // Hindu gods
  "Brahma",
  "Vishnu",
  "Shiva",
  "Ganesha",
  "Indra",
  "Kali",
  "Durga",
  "Lakshmi",
  "Saraswati",
  "Yama",
  "Hanuman",
  "Varuna",
  
  // Chinese gods
  "Jade Emperor",
  "Yu Di",
  "Shangdi",
  "Chang'e",
  "Nezha",
  "Zhu Rong",
  "Hebo",
  "Pangu",
  "Lei Gong",
  "Zhong Kui",
  "Kuan Yin",
  "Taiyi",
  
  // Japanese gods
  "Amaterasu",
  "Izanami",
  "Izanagi",
  "Susano-o",
  "Raijin",
  "Fujin",
  "Inari",
  "Benten",
  "Hotei",
  "Ebisu",
  "Kuebiko",
  "Ryujin",
  
  // Mesopotamian gods
  "Anu",
  "Enki",
  "Enlil",
  "Marduk",
  "Nanna",
  "Tiamat",
  "Ishtar",
  "Nergal",
  "Gilgamesh",
  "Nabu",
  "Ninhursag",
  "Utu",
  
  // Aztec gods
  "Huitzilopochtli",
  "Quetzalcoatl",
  "Tlaloc",
  "Tezcatlipoca",
  "Xipe Totec",
  "Coatlicue",
  "Mictlantecuhtli",
  "Xochiquetzal",
  "Chalchiuhtlicue",
  "Itztlacoliuhqui",
  "Tonatiuh",
  "Chantico",
  
  // African gods
  "Anansi",
  "Mami Wata",
  "Anansi",
  "Mami Wata",
  "Oya",
  "Shango",
  "Legba",
  "Oshun",
  "Osanyin",
  "Ogun",

//bible
  "God",
  "Jesus",
  "Holy Spirit",
  "Angels",
  "Satan",
  "Demons",
  "Seraphim",
  "Cherubim",
  "Nephilim",
  "Leviathan",
  "Behemoth",
  "Rephaim",
  "Ziz",
  "Abaddon",
  "Apollyon",
  "Beelzebub",
  "Belial",
  "Mammon",
  "Asmodeus",
  "Astaroth",
  "Baal",
  "Azazel",
  "Samael",
  "Lilith",
  "Lucifer",
  "Abraham's Bosom",
  "Gehenna",
  "Hades",
  "Lake of Fire",
  "New Jerusalem",
  "Paradise",
  "Sheol",
  "Tree of Life",
  "Tree of Knowledge of Good and Evil",
  "Ahab's spirit",
  "Samuel's spirit",
  "Witch of Endor's spirit",
  "Balaam's donkey",
  "Burning bush",
  "Pillar of cloud",
  "Pillar of fire",
  "Rainbow around the throne",
  "Urim and Thummim",
  "Brazen serpent",
  "Golden calf",
  "Manna",
  "Aaron's rod",
  "Tabernacle",
  "Ark of the Covenant",
  "Mercy seat",
  "Cherubim on the ark",
  "Bronze laver",
  "Altar of burnt offering",
  "Table of showbread",
  "Candlestick",
  "Veil of the Tabernacle",
  "Ephod",
  "Breastplate of judgment",
  "Anointing oil",
  "Bowl of incense",
  "Lampstand of the Tabernacle",
  "Mercy seat of the Tabernacle",
  "Cloud of glory",
  "Fiery furnace",
  "Handwriting on the wall",
  "Lion's den",
  "Sodom and Gomorrah",
  "Plagues of Egypt",
  "Parting of the Red Sea",
  "Samson's strength",
  "Shadrach, Meshach, and Abednego in the fiery furnace",
  "Jacob's ladder",
  "Joseph's ability to interpret dreams",
  "Moses' staff turning into a snake",
  "Moses' hand becoming leprous",
  "Moses' parting of the Jordan River",
  "Elijah's fire from heaven",
  "Elisha's healing of Naaman's leprosy",
  "Elisha's floating axe head",
  "Jonah and the great fish",
  "Daniel in the lion's den",
  "Daniel's ability to interpret dreams",
  "Goliath",
  "Solomon's wisdom",
  "Gideon's fleece",
  "Balaam's talking donkey",
  "Joshua and the walls of Jericho",
  "Samuel's prophecy",
  "Isaiah's prophecy",
  "Jeremiah's prophecy",
  "Ezekiel's vision",
  "The four horsemen of the apocalypse",
  "The mark of the beast",
  "The Whore of Babylon",
  "The Beast from the Sea",
  "The Beast from the Earth",
  "The False Prophet",
  "The Two Witnesses",
  "The Four Living Creatures",
  "The 24 Elders",
  "Mount Sinai",
"Mount of Transfiguration",
"Jordan River",
"Sea of Galilee",
"Dead Sea",
"Garden of Gethsemane",
"Mount of Olives",
"Mount Zion",
"Mount Moriah",
"Valley of Megiddo",
"Valley of Jehoshaphat",
"Valley of Dry Bones",
"The Red Heifer",
"The Water of Purification",
"The Brazen Serpent",
"The Tabernacle of David",
"The Temple of Solomon",
"The Temple of Zerubbabel",
"The Temple of Herod",
"The Ark of Noah",
"The Tower of Babel",
"The Walls of Jericho",
"The Gates of Hades",
"The Gates of Zion",
"The Gates of Jerusalem",
"The Gates of Heaven",
"The Seven Trumpets",
"The Seven Seals",
"The Seven Bowls",
"The Ten Plagues of Egypt",
"The Ten Commandments",
"The Twelve Tribes of Israel",
"The Twelve Apostles",
"The Twelve Prophets",
"The Four Archangels",
"The Seven Spirits of God",
"The Ten Horns",
"The Dragon",
"The Lamb of God",
"The Lion of Judah",
"The Root of Jesse",
"The Morning Star",
"The Alpha and the Omega",
"The First and the Last",
"The Word of God",
"The Son of Man",
"The Messiah",
"The Redeemer",
"The Suffering Servant",
"The High Priest",
"The Bread of Life",
"The Living Water",
"The Light of the World",
"The Good Shepherd",
"The Vine",
"The Way, the Truth, and the Life",
"The Prince of Peace",
"The Judge of the Living and the Dead",
"The Resurrection and the Life",
"The Bridegroom",
"The Advocate",
"The Comforter",
"The Spirit of Truth",
"The Power of God",
"The Wisdom of God",
"The Glory of God",
"The Love of God",
"The Host of Heaven",  
"The Angel of the Lord",  
"The Angel Gabriel",  
"The Angel Michael",  
"The Angel Raphael",  
"The Cherubim",  
"The Seraphim",  
"The Nephilim",  
"The Watchers",  
"The Principalities",  
"The Powers",  
"The Thrones",  
"The Dominions",  
"The Virtues",  
"The Orders of Angels",  
"The Demons",  
"Satan",  
"Beelzebul",  
"Legion",  
"Mammon",  
"Belial",  
"Asmodeus",  
"Leviathan",  
"Behemoth",  
"Abaddon",  
"Apollyon",  
"The Beast",  
"The False Prophet",  
"The Antichrist",  
"The Great Harlot",  
"The Abomination of Desolation",  
"The Man of Lawlessness",  
"The Son of Perdition",  
"The Prince of this World",  
"The Father of Lies",  
"The Accuser",  
"The Adversary",  
"The Tempter",  
"The Evil One",  
"The Wicked One",  
"The Destroyer",  
"The Angel of Death",  
"The King of Terrors",  
"The Grave",  
"The Pit",  
"The Lake of Fire",  
"The Second Death",  
"The Abyss",  
"The Bottomless Pit",  
"The Outer Darkness",  
"The Place of Weeping and Gnashing of Teeth",  
"The Valley of Hinnom",  
"The Gehenna",  
"The Sheol",  
"The Hades",  
"The Tartarus",  
"The Paradise",  
"The Bosom of Abraham",  
"The New Jerusalem",  
"The City of God",  
"The Kingdom of Heaven",  
"The Kingdom of God",  
"The Celestial City",  
"The Heavenly Jerusalem",  
"The Holy City",  
"The Bride of Christ",  
"The New Heaven and the New Earth",  
"The Tree of Life",  
"The River of Life",  
"The Mansions in Heaven",  
"The Crown of Life",  
"The Crown of Glory",  
"The Crown of Righteousness",  
"The Pearl of Great Price",  
"The Hidden Manna",  
"The White Stone with a New Name",  
"The Morning Star",
"The Ancient of Days",  
"The Alpha and Omega",  
"The Beginning and the End",  
"The First and the Last",  
"The Word of God",  
"The Lamb of God",  
"The Lion of the Tribe of Judah",  
"The Root of Jesse",  
"The Branch",  
"The Suffering Servant",  
"The Messiah",  
"The Christ",  
"The Anointed One",  
"The Holy One",  
"The Holy Spirit",  
"The Comforter",  
"The Spirit of Truth",  
"The Spirit of Wisdom",  
"The Spirit of Understanding",  
"The Spirit of Counsel",  
"The Spirit of Power",  
"The Spirit of Knowledge",  
"The Spirit of the Fear of the Lord",  
"The Seven Spirits of God",  
"The Spirit of Life",  
"The Spirit of Grace",  
"The Spirit of Prophecy",  
"The Spirit of Adoption",  
"The Spirit of Holiness",  
"The Spirit of Jesus Christ",  
"The Spirit of Glory",  
"The Spirit of Fire",  
"The Spirit of Judgment",  
"The Spirit of Faith",  
"The Spirit of Love",  
"The Spirit of Unity",  
"The Spirit of Peace",  
"The Spirit of Liberty",  
"The Spirit of Prayer",  
"The Spirit of Praise",  
"The Spirit of the Lord",  
"The Spirit of Elijah",  
"The Spirit of Elisha",  
"The Spirit of Moses",  
"The Spirit of Joshua",  
"The Spirit of Caleb",  
"The Spirit of Deborah",  
"The Spirit of Gideon",  
"The Spirit of Samson",  
"The Spirit of David",  
"The Spirit of Solomon",  
"The Spirit of Isaiah",  
"The Spirit of Jeremiah",  
"The Spirit of Ezekiel",  
"The Spirit of Daniel",  
"The Spirit of Hosea",  
"The Spirit of Joel",  
"The Spirit of Amos",  
"The Spirit of Obadiah",  
"The Spirit of Jonah",  
"The Spirit of Micah",  
"The Spirit of Nahum",  
"The Spirit of Habakkuk",  
"The Spirit of Zephaniah",  
"The Spirit of Haggai",  
"The Spirit of Zechariah",  
"The Spirit of Malachi",


"The Destroyer",  
"The Avenger",  
"The Angel of the Lord",  
"The Angel of Death",  
"The Watchers",  
"The Nephilim",  
"The Serpent",  
"The Dragon",  
"The Leviathan",  
"The Behemoth",  
"The Beast",  
"The False Prophet",  
"The Antichrist",  
"The Abaddon",  
"The Apollyon",  
"The Prince of this World",  
"The Father of Lies",  
"The Deceiver",  
"The Adversary",  
"The Tempter",  
"The Accuser",  
"The Slanderer",  
"The Wicked One",  
"The Evil One",  
"The Unclean Spirit",  
"The Foul Spirit",  
"The Spirit of Antichrist",  

/*
"The Spirit of Error",  
"The Spirit of Divination",  
"The Spirit of Python",  
"The Spirit of Bondage",  
"The Spirit of Fear",  
"The Spirit of Jealousy",  
"The Spirit of Whoredom",  
"The Spirit of Error",  
"The Spirit of Infirmity",  
"The Spirit of Burning",  
"The Spirit of Judgment",  
"The Spirit of Wisdom and Revelation",  
"The Spirit of Might",  
"The Spirit of Glory and of God",  
"The Spirit of Truth and of Power",  
"The Spirit of Holiness and of Life",  
"The Spirit of Adoption and of Grace",  
"The Spirit of Resurrection and of Life",  
"The Spirit of Promise and of Faith",  
"The Spirit of Comfort and of Peace",  
"The Spirit of Supplication and of Intercession",  
"The Spirit of Forgiveness and of Love",  
"The Spirit of Restoration and of Healing",  
"The Spirit of Sanctification and of Righteousness",  
"The Spirit of Renewal and of Transformation",  
"The Spirit of Unity and of Oneness",  
"The Spirit of Revival and of Awakening",  
"The Spirit of Redemption and of Salvation",  
"The Spirit of the Bride and of the Bridegroom",  
"The Spirit and the Bride say, Come!", 

"The Spirit of Life",  
"The Spirit of Christ",  
"The Spirit of God",  
"The Spirit of the Lord",  
"The Spirit of Elijah",  
"The Spirit of the Prophets",  
"The Spirit of Grace",  
"The Spirit of Power",  
"The Spirit of Knowledge",  
"The Spirit of Understanding",  
"The Spirit of Counsel",  
"The Spirit of Wisdom",  
"The Spirit of Prophecy",  
"The Spirit of Healing",  
"The Spirit of Deliverance",  
"The Spirit of Freedom",  
"The Spirit of Comfort",  
"The Spirit of Joy",  
"The Spirit of Peace",  
"The Spirit of Hope",  
"The Spirit of Faith",  
"The Spirit of Love",  
"The Spirit of Unity",  
"The Spirit of Humility",  
"The Spirit of Meekness",  
"The Spirit of Patience",  
"The Spirit of Gentleness",  
"The Spirit of Self-Control",  
"The Spirit of Righteousness",  
"The Spirit of Holiness",  
"The Spirit of Perseverance",  
"The Spirit of Endurance",  
"The Spirit of Courage",  
"The Spirit of Boldness",  
"The Spirit of Obedience",  
"The Spirit of Truth",  
"The Spirit of Life in Christ Jesus",  
"The Spirit of the Fear of the Lord",  
"The Spirit of Judgment and of Burning",  
"The Spirit of Glory and of Fire",  
"The Spirit of Adoration and of Worship",  
"The Spirit of Praise and of Thanksgiving",  
"The Spirit of Gratitude and of Blessing",  
"The Spirit of Honor and of Reverence",  
"The Spirit of Encouragement and of Edification",  
"The Spirit of Teaching and of Discipleship",  
"The Spirit of Guidance and of Direction",  
"The Spirit of Conviction and of Repentance",  
"The Spirit of Intercession and of Prayer",  
"The Spirit of Evangelism and of Missions",  
"The Spirit of Discernment and of Wisdom",  
"The Spirit of Forgiveness and of Reconciliation",  
"The Spirit of Service and of Sacrifice",  
"The Spirit of Leadership and of Authority",  
"The Spirit of Creativity and of Innovation",  
"The Spirit of Excellence and of Mastery",  
"The Spirit of Miracles and of Signs",  
"The Spirit of Restoration and of Renewal",  
"The Spirit of Resurrection and of Life",  
"The Spirit of Transformation and of Renewal",  
"The Spirit of Unity and of Oneness",  
"The Spirit of Revival and of Awakening",  
"The Spirit of Redemption and of Salvation",  
"The Spirit of the Bride and of the Bridegroom",  
"The Spirit and the Bride say, Come!"
*/];