module.exports = [
"bong", 
"pipe", 
"joint", 
"blunt", 
"glass pipe", 
"bubbler", 
"coke can", 
"gravity bong", 
"water bong", 
"water pipe", 
"aluminum foil pipe", 
"peace pipe", 
"spliff", 
"vape pen", 
"6-foot bong", 
"foot-long joint"];