module.exports = ["2 Chainz",
  "21 Savage",
  "50 Cent",
  "A$AP Ferg",
  "A$AP Rocky",
  "Action Bronson",
  "Andre 3000",
  "ASAP Nast",
  "B.o.B",
  "Beastie Boys",
  "Big Boi",
  "Big Daddy Kane",
  "Big K.R.I.T.",
  "Big L",
  "Big Pun",
  "Big Sean",
  "Biz Markie",
  "Bizzy Bone",
  "Black Thought",
  "Busta Rhymes",
  "Cam'ron",
  "Cardi B",
  "Chance the Rapper",
  "Childish Gambino",
  "Common",
  "Coolio",
  "Cypress Hill",
  "DaBaby",
  "Danny Brown",
  "Dave East",
  "De La Soul",
  "Dead Prez",
  "Death Grips",
  "Del the Funky Homosapien",
  "Deniro Farrar",
  "Denzel Curry",
  "Desiigner",
  "Digable Planets",
  "DJ Jazzy Jeff & The Fresh Prince",
  "DJ Khaled",
  "DMX",
  "Dr. Dre",
  "Drake",
  "E-40",
  "Earl Sweatshirt",
  "Eazy-E",
  "Eminem",
  "Eric B. & Rakim",
  "Fat Joe",
  "Fetty Wap",
  "Flavor Flav",
  "Flo Rida",
  "Future",
  "G-Eazy",
  "Gang Starr",
  "Ghostface Killah",
  "Gorillaz",
  "Grandmaster Flash and the Furious Five",
  "Gucci Mane",
  "Guru",
  "Ice Cube",
  "Ice-T",
  "Insane Clown Posse",
  "J. Cole",
  "Ja Rule",
  "Jay Electronica",
  "Jay-Z",
  "Jeezy",
  "Joey Bada$$",
  "Juice WRLD",
  "Kanye West",
  "Kendrick Lamar",
  "Kid Cudi",
  "Killer Mike",
  "King Geedorah",
  "King Von",
  "Kool G Rap",
  "KRS-One",
  "Lauryn Hill",
  "Lil Baby",
  "Lil Kim",
  "Lil Nas X",
  "Lil Uzi Vert",
  "Lil Wayne",
  "LL Cool J",
  "Logic",
  "Ludacris",
  "Lupe Fiasco",
  "M.O.P.",
  "Macklemore",
  "Madlib",
  "Mase",
  "MC Hammer",
  "MC Lyte",
  "MC Ren",
  "Meek Mill",
  "MF DOOM",
  "Migos",
  "Missy Elliott",
  "Mos Def",
  "Nas",
  "Nate Dogg",
  "Nelly",
  "Nicki Minaj",
  "Notorious B.I.G.",
  "NWA",
  "Oddisee",
  "Ol' Dirty Bastard",
  "Outkast",
  "P. Diddy",
  "Pete Rock & CL Smooth",
  "Pharrell Williams",
  "Playboi Carti",
  "Post Malone",
  "Prodigy",
  "Public Enemy",
  "Pusha T",
  "Queen Latifah",
  "Raekwon",
   "Redman",
  "Rich Brian",
  "Rick Ross",
  "Run-DMC",
  "Saba",
  "Salt-N-Pepa",
  "Schoolboy Q",
  "Snoop Dogg",
  "Soulja Boy",
  "Statik Selektah",
  "Stormzy",
  "Swae Lee",
  "T.I.",
  "Tech N9ne",
  "The Alchemist",
  "The Game",
  "The Pharcyde",
  "The Roots",
  "Three 6 Mafia",
  "Tory Lanez",
  "Travis Scott",
  "Tribe Called Quest",
  "Trippie Redd",
  "Tupac Shakur",
  "Twista",
  "Tyler, The Creator",
  "U-God",
  "Vince Staples",
  "Wale",
  "Warren G",
  "Wiz Khalifa",
  "Wu-Tang Clan",
  "Xzibit",
  "YBN Cordae",
  "Yelawolf",
  "YG",
  "Young Jeezy",
  "Young Thug",
  "Yung Lean"];