module.exports = [
"Art Nouveau", 
"Conceptual Art", 
"greek art", 
"aztec art", 
"max fleisher", 
"Dadaism", 
"horror", 
"nightmare", 
"horrorcore", 
"synthwave", 
"photographic",
"shodo",
"ukiyo-e",
"terra-cotta",
"pixel",
"pop art",
"posterized",
"logo art",
"t-shirt art",
"fat sloppy lines",
"charcoal",
"stop-motion",
"paper cut-outs",
"canvas",
"straight lines",
"anime",
"m.c. escher",
"photorealism",
"absurdism",
't-shirt design',
'golden gold on gold',
"hat design",
"fresco",
"fashion brand",
'classical art',
"dark evil", 
"Harlem Renaissanc", 
"Minimalism", 
"Jessica Walsh", 
"Michael Bierut", 
"Mosaic art technique",
"Benoy Sarkar",
"Molly McCoy", 
"rastafarian",
"hindu art",
"picasso",
"Haboku",
"collage",
"Plique-à-jour enameling technique",
"dr. suess",
"movie poster",
"book cover",
"adult comic book",
"Norman Rockwell", 
"Hayao Miyazaki", 
"william blake",
"Beatrix Potter", 
"Quentin Blake", 
"Vermeer", 
"Georges Seurat", 
"andy warhol", 
"Rembrandt", 
"futuristic", 
"punk", 
"basquiat", 
"frank miller", 
"salvadore dali", 
"hippie art",
"trippy lsd",
"black and white",
"abstract",
"Realism", 
"Impressionism", 
"Post-Impressionism", 
'Henri Matisse',
"Expressionism", 
"Cubism", 
"Surrealism", 
"Abstract Expressionism", 
"Pop Art", 
"Minimalism", 
"Conceptual Art", 
"Op Art", 
"Performance Art", 
"Street Art", 
"Graffiti Art", 
"Installation Art", 
"Land Art", 
"Digital Art", 
"New Media Art", 
"Contemporary Art", 
"Outsider Art",
"Salvador Dali", 
"Surrealism", 
"Pablo Picasso", 
"Cubism", 
"Vincent van Gogh", 
"Post-Impressionism", 
"Frida Kahlo", 
"Naive Art", 
"Henri Matisse", 
"Fauvism", 
"Jean-Michel Basquiat", 
"Graffiti Art", 
"Banksy", 
"Street Art", 
"Edvard Munch", 
"Expressionism", 
"Gustav Klimt", 
"Art Nouveau", 
"René Magritte", 
"Surrealism", 
"Marc Chagall", 
"Modernism", 
"Wassily Kandinsky", 
"Abstract Art", 
"Paul Cézanne", 
"Post-Impressionism", 
"Amedeo Modigliani", 
"Modernism", 
"Egon Schiele", 
"Expressionism", 
"Joan Miró", 
"Surrealism", 
"Henri de Toulouse-Lautrec", 
"Post-Impressionism", 
"Frédéric Bazille", 
"Impressionism", 
"Georgia O’Keeffe", 
"American Modernism", 
"Mary Cassatt", 
"Impressionism", 
"Willem de Kooning", 
"Abstract Expressionism", 
"Jackson Pollock", 
"Action Painting", 
"Mark Rothko", 
"Color Field Painting", 
"Robert Rauschenberg", 
"Dada", 
"Roy Lichtenstein", 
"Pop Art", 
"Claes Oldenburg", 
"Pop Art", 
"Tom Wesselmann", 
"Pop Art", 
"Jim Dine", 
"Pop Art", 
"Ed Ruscha", 
"Pop Art", 
"David Hockney", 
"Pop Art", 
"Jasper Johns", 
"Neo-Dada", 
"Robert Indiana", 
"Pop Art", 
"Richard Hamilton", 
"Pop Art", 
"Yoko Ono", 
"Fluxus", 
"Niki de Saint Phalle", 
"Naive Art", 
"Keith Haring", 
"Graffiti Art", 
"Jean Dubuffet", 
"Art Brut", 
"Max Ernst", 
"Surrealism", 
"Paul Klee", 
"Expressionism", 
"James Rosenquist", 
"Pop Art", 
"Daniel Arsham", 
"Architectural Art", 
"Liu Bolin", 
"Invisible Art", 
"Ai Weiwei", 
"Political Art", 
"Banksy", 
"Street Art", 
"Jenny Holzer", 
"Conceptual Art"]