module.exports = [
"Agent Orange strain",
"Agent Orange",
"AK-47",
"AK-48",
"Alien Dawg strain",
"Alien OG strain",
"Amnesia Haze strain",
"Banana Kush strain",
"Banana OG strain",
"banger",
"Biscotti strain",
"Black Widow strain",
"Blackberry Kush",
"Blackberry strain",
"Blue Cheese strain",
"Blue Cheese",
"Blue Dream",
"Blueberry Kush strain",
"Blueberry Kush",
"Blueberry",
"Blunt",
"Bong",
"Bowl",
"Bruce Banner #3 strain",
"Bruce Banner",
"Bubba Kush",
"Bubble Gum",
"Bud rot",
"Bud trimmer",
"Budder",
"Budtender",
"Budtography",
"cake",
"Candyland strain",
"Cannabinoid profile",
"Cannabinoids",
"Cannabis activism",
"Cannabis cocktail",
"Cannabis connoisseur",
"Cannabis Cup",
"Cannabis extracts",
"Cannabis oil cartridges",
"Cannabis topicals",
"Cannabis tourism",
"Cannabis",
"Cannabis-infused beverages",
"Cannabis-infused massage oil",
"Cannabutter",
"Cannatonic",
"cap",
"Caramelicious strain",
"CBD",
"CBG",
"CBN",
"Champagne Kush strain",
"Chem Scout strain",
"Chemdawg",
"Chemdog strain",
"Chernobyl strain",
"Cherry AK-47 strain",
"Cherry AK-47",
"Cherry Kush strain",
"Cherry Pie",
"Chocolate Thai strain",
"Chocolope strain",
"Chocolope",
"Chronic",
"collector",
"Concentrates",
"Cookies",
"Cottonmouth",
"Couch lock",
"Dab nail",
"Dab rig",
"Dabbing",
"Dank",
"Decarboxylation",
"Diesel",
"Dime bag",
"Dispensary",
"Dosidos strain",
"Dream",
"Dub sack",
"Durban Poison",
"Dutch Treat strain",
"Edibles",
"effect",
"Enail",
"Entourage effect",
"Express",
"extraction",
"Feminized seeds",
"Fire OG strain",
"Flavonoids",
"G13 Haze strain",
"G13",
"Ganja",
"Gelato #33 strain",
"Gelato strain",
"Gelato",
"Girl Scout Cookies",
"Gold",
"Golden Goat",
"Gorilla Breath strain",
"Gorilla Glue #4",
"Gorilla glue strain",
"Granddaddy Purple",
"Grape Ape strain",
"Grapefruit strain",
"Green Crack",
"Green dragon",
"Grinder",
"GSC (formerly known as Girl Scout Cookies)",
"Gummy bears",
"Gushers strain",
"Hash",
"Hashish",
"Haze",
"Headband",
"Hemp",
"Herb",
"Herer",
"High",
"Hindu Kush",
"Hotboxing",
"Hybrid",
"Ice Cream Cake strain",
"Indica",
"Indica-dominant",
"Isolate",
"Jack Herer",
"Jane",
"Joint",
"Kief",
"Kush",
"Landrace",
"Laughing Buddha strain",
"Lava Cake strain",
"Lavender strain",
"Leafly",
"Lemon Haze",
"Lemon Kush strain",
"Lemon Skunk strain",
"Lights",
"Live resin",
"LSD",
"Mango Kush strain",
"Maui Wowie",
"Mimosa strain",
"Moon rocks",
"Moonshine Haze strain",
"Munchies",
"nail",
"Northern Lights",
"Nugs",
"OG Kush",
"oil",
"One-hitter",
"Orange Crush strain",
"Papaya strain",
"Paranoia",
"percentage",
"Peyote Cookies strain",
"Pineapple Express strain",
"Pineapple Express",
"Pipe",
"Platinum Girl Scout Cookies",
"Platinum Kush strain",
"Pot",
"Pre-rolls",
"profile",
"Purple Haze",
"Purple Kush",
"Purple Punch strain",
"Purple Tangie strain",
"Purple Urkle strain",
"Reefer",
"Resin glands",
"Resin",
"resin",
"rig",
"Roach",
"rock",
"Rolling papers",
"Rosin press",
"Rosin tech",
"Rosin",
"Runtz strain",
"Sage strain",
"Sativa",
"Sativa-dominant",
"Sensi Star",
"Shatter",
"Skunk",
"Skywalker OG",
"Sour Diesel",
"Sour OG strain",
"Sour Tangie strain",
"Space cake",
"spectrum",
"Spliff",
"Sticky icky",
"Stoned",
"Stoner",
"Strain",
"Strawberry Banana strain",
"Strawberry Cough",
"Sundae Driver strain",
"Super Lemon Haze",
"Super Silver Haze",
"Super Skunk strain",
"syrup",
"Tahoe Alien strain",
"Tahoe OG",
"Tangie",
"Terpene profile",
"Terpenes",
"THC tolerance",
"THC",
"THCV",
"Tincture",
"Topicals",
"Torch lighter",
"Trainwreck",
"Trichome farming",
"Trichomes",
"Vape cartridge",
"Vape pen",
"Vaporizer",
"Wake and bake",
"WaterBong",
"Wax",
"Wedding Cake",
"Weed brownies",
"Weed",
"Weedmaps",
"White Fire OG strain",
"White Rhino",
"White Widow strain",
"White Widow",
"Widow",
"Wowie",
"Zkittlez strain",
"Zombie OG strain",
]