module.exports = [  
"Witch",
"Ghost",  
"Vampire",  
"Zombie",  
"Catwoman",  
"Batgirl",  
"Harley Quinn",  
"Wonder Woman",  
"Poison Ivy",  
"Cruella de Vil",  
"Skeleton",  
"Mummy",  
"Frankenstein",  
"Bride of Frankenstein",  
"Mermaid",  
"Fairy",  
"Angel",  
"Devil",  
"Pirate",  
"Ninja",  
"Egyptian queen",  
"Geisha",  
"Disco diva",  
"80s pop star",  
"90s grunge rocker",  
"Rockstar",  
"Pop star",  
"Princess",  
"Queen",  
"Duchess",  
"Goddess",  
"Femme fatale",  
"Red Riding Hood",  
"Alice in Wonderland",  
"Mad Hatter",  
"Queen of Hearts",  
"Cheshire Cat",  
"Tinkerbell",  
"Peter Pan",  
"Captain Hook",    
"Daisy Duck",  
"Snow White",  
"Cinderella",  
"Ariel",  
"Belle",  
"Jasmine",  
"Mulan",  
"Moana",  
"Elsa",  
"Anna",  
"Maleficent",  
"Ursula",  
"Cruella",  
"Jessica Rabbit",  
"Betty Boop",  
"Barbie",  
"Doll",  
"Rag Doll",  
"Robot",  
"Alien",  
"Star Wars character",  
"Superhero",  
//"Power Ranger",  
"Nurse",  
"Doctor",  
"Police officer",  
"Firefighter",  
"Pilot",  
"Flight attendant",  
"Chef",  
"Baker",  
"Waitress",  
"Maid",  
"Schoolgirl",  
"Cheerleader",  
"Gymnast",  
"Ballerina",  
"Figure skater",  
"Boxer",  
"Wrestler",  
"Football player",  
"Basketball player",  
"Baseball player",  
"Tennis player",  
"Golfer",  
"Race car driver",  
"Cowgirl",  
"Indian princess",  
"Hula dancer",  
"Belly dancer",  
"Salsa dancer",  
"Hip hop dancer",  
"Breakdancer"];